-- Enable the pgvector extension to work with embedding vectors
create extension if not exists vector;

-- Create the github_issues table for RAG matchmaking
create table if not exists github_issues (
  id bigint generated by default as identity primary key,
  github_id bigint not null unique,
  org_name text not null,
  repo_name text not null,
  title text not null,
  body text,
  url text not null,
  state text not null,
  labels jsonb,
  -- We use text-embedding-3-small which outputs 1536 dimensions
  embedding vector(1536),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create a function to search for issues based on similarity
create or function match_github_issues(
  query_embedding vector(1536),
  match_threshold float,
  match_count int
)
returns table (
  id bigint,
  org_name text,
  repo_name text,
  title text,
  url text,
  similarity float
)
language sql stable
as $$
  select
    github_issues.id,
    github_issues.org_name,
    github_issues.repo_name,
    github_issues.title,
    github_issues.url,
    1 - (github_issues.embedding <=> query_embedding) as similarity
  from github_issues
  where 1 - (github_issues.embedding <=> query_embedding) > match_threshold
  order by github_issues.embedding <=> query_embedding
  limit match_count;
$$;

-- Enable RLS
alter table github_issues enable row level security;

-- Allow public read access (Matchmaking is a public feature)
create policy "Allow public read-only access to github_issues" 
  on github_issues for select using (true);
